apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: ibm-mq
  namespace: openshift-operators
spec:
  channel: v2.2
  name: ibm-mq
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace
