apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: is01
  namespace: acemq
spec:
  adminServerSecure: true
  createDashboardUsers: true
  designerFlowsOperationMode: disabled
  enableMetrics: true
  license:
    accept: true
    license: L-APEH-CFZE47
    use: CloudPakForIntegrationProduction
  pod:
    containers:
      runtime:
        resources:
          limits:
            cpu: 300m
            memory: 368Mi
          requests:
            cpu: 300m
            memory: 368Mi
  replicas: 1
  router:
    timeout: 120s
  service:
    endpointType: http
  version: '12.0'
  barURL: ''
  configurations: []
