apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: platformui-aws-secret-manager
  namespace: cp4i
  annotations:
    argocd.argocd.io/sync-wave: "-4"
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: Base64
      key: certs/cp4i/cp-platform-ui
      property: ca_crt
    secretKey: ca.crt
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: Base64
      key: certs/cp4i/cp-platform-ui
      property: tls_crt
    secretKey: tls.crt
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: Base64
      key: certs/cp4i/cp-platform-ui
      property: tls_key
    secretKey: tls.key
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: externalsecretstore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: platformui-tls-secret
