apiVersion: datapower.ibm.com/v1beta3
kind: DataPowerService
metadata:
  name: datapower
  namespace: ${namespace}
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector: {}
            topologyKey: topology.kubernetes.io/zone
          weight: 100
  domains:
  - name: "default"
    dpApp:
      config:
      - "web-mgmt"
  license:
    accept: true
    license: L-RJON-CCAT5F
    use: ${licensetype}
  replicas: ${replicas}
  resources:
    limits:
      memory: 8Gi
    requests:
      cpu: 4
      memory: 4Gi
  users:
    - accessLevel: privileged
      name: admin
      passwordSecret: admin-secret
  version: 10.5-lts
