apiVersion: v1
kind: Namespace
metadata:
  name: ${namespace}
  annotations:
    argocd.argocd.io/sync-wave: "-5"
    openshift.io/node-selector: ${nodelabel}
  labels:
    argocd.argoproj.io/managed-by: gitops-cluster
