apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cpconsole-aws-secret-manager
  namespace: ibm-common-services
  annotations:
    argocd.argocd.io/sync-wave: "-1"
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: Base64
      key: certs/cp4i/cp-console
      property: ca_crt
    secretKey: ca.crt
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: Base64
      key: certs/cp4i/cp-console
      property: tls_crt
    secretKey: tls.crt
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: Base64
      key: certs/cp4i/cp-console
      property: tls_key
    secretKey: tls.key
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: externalsecretstore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: cpconsole-tls-secret
